<?php

namespace Database\Seeders;

use App\enum\MealCategory;
use App\Models\Category;
use App\Models\Meal;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MealsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category IDs
        $chickenCategory = Category::where('slug', 'chicken-meals')->first();
        $beefLambCategory = Category::where('slug', 'beef-lamb-meals')->first();
        $fishCategory = Category::where('slug', 'fish-meals')->first();
        $vegetarianCategory = Category::where('slug', 'vegetarian-meals')->first();

        if (!$chickenCategory || !$beefLambCategory || !$fishCategory || !$vegetarianCategory) {
            $this->command->error('Categories not found. Please run CategoriesSeeder first.');
            return;
        }

        $meals = [
            // Chicken Meals (Menu - Type 0) - 5 meals
            [
                'name' => 'Grilled Chicken Breast with Vegetables',
                'slug' => 'grilled-chicken-breast-vegetables',
                'description' => 'Tender grilled chicken breast served with seasonal roasted vegetables and herbs',
                'short_description' => 'Healthy grilled chicken with veggies',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 450,
                'protein' => 45.00,
                'carbohydrates' => 25.00,
                'fats' => 15.00,
                'fiber' => 6.00,
                'sodium' => 450.00,
                'sugar' => 4.00,
                'ingredients' => ['Chicken breast', 'Broccoli', 'Carrots', 'Olive oil', 'Herbs'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 25,
                'difficulty_level' => 2,
                'price' => 45.00,
                'weight_grams' => 400,
                'serving_size' => '1 portion',
                'is_active' => true,
                'show_for_membership' => true,
            ],
            [
                'name' => 'Chicken Tagine with Olives',
                'slug' => 'chicken-tagine-olives',
                'description' => 'Traditional Moroccan chicken tagine with olives, preserved lemons and aromatic spices',
                'short_description' => 'Moroccan chicken tagine',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 520,
                'protein' => 42.00,
                'carbohydrates' => 35.00,
                'fats' => 22.00,
                'fiber' => 5.00,
                'sodium' => 680.00,
                'sugar' => 6.00,
                'ingredients' => ['Chicken thighs', 'Green olives', 'Preserved lemons', 'Onions', 'Spices'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 45,
                'difficulty_level' => 3,
                'price' => 52.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
                                'show_for_membership' => true,

            ],
            [
                'name' => 'Chicken Curry with Rice',
                'slug' => 'chicken-curry-rice',
                'description' => 'Creamy chicken curry with aromatic spices served with basmati rice',
                'short_description' => 'Spicy chicken curry',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 580,
                'protein' => 38.00,
                'carbohydrates' => 62.00,
                'fats' => 18.00,
                'fiber' => 4.00,
                'sodium' => 720.00,
                'sugar' => 5.00,
                'ingredients' => ['Chicken', 'Coconut milk', 'Curry spices', 'Basmati rice', 'Onions', 'Tomatoes'],
                'allergens' => [],
                'is_spicy' => true,
                'spice_level' => 3,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 2,
                'price' => 48.00,
                'weight_grams' => 500,
                'serving_size' => '1 portion',
                'is_active' => true,
                                'show_for_membership' => true,

            ],
            [
                'name' => 'Lemon Herb Chicken Skewers',
                'slug' => 'lemon-herb-chicken-skewers',
                'description' => 'Marinated chicken skewers with lemon and fresh herbs, served with quinoa',
                'short_description' => 'Grilled chicken skewers',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 420,
                'protein' => 40.00,
                'carbohydrates' => 28.00,
                'fats' => 14.00,
                'fiber' => 5.00,
                'sodium' => 380.00,
                'sugar' => 2.00,
                'ingredients' => ['Chicken breast', 'Lemon', 'Herbs', 'Quinoa', 'Bell peppers'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 15,
                'difficulty_level' => 2,
                'price' => 46.00,
                'weight_grams' => 380,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Chicken Pasta Alfredo',
                'slug' => 'chicken-pasta-alfredo',
                'description' => 'Creamy Alfredo pasta with grilled chicken and parmesan cheese',
                'short_description' => 'Creamy chicken pasta',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 680,
                'protein' => 42.00,
                'carbohydrates' => 58.00,
                'fats' => 32.00,
                'fiber' => 3.00,
                'sodium' => 820.00,
                'sugar' => 4.00,
                'ingredients' => ['Chicken breast', 'Pasta', 'Heavy cream', 'Parmesan', 'Garlic', 'Butter'],
                'allergens' => ['Gluten', 'Dairy'],
                'prep_time_minutes' => 10,
                'cooking_time_minutes' => 20,
                'difficulty_level' => 2,
                'price' => 50.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Beef/Lamb Meals (Menu - Type 0) - 5 meals
            [
                'name' => 'Beef Bourguignon',
                'slug' => 'beef-bourguignon',
                'description' => 'Classic French beef stew braised in red wine with mushrooms and pearl onions',
                'short_description' => 'French beef stew',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 620,
                'protein' => 48.00,
                'carbohydrates' => 32.00,
                'fats' => 28.00,
                'fiber' => 4.00,
                'sodium' => 780.00,
                'sugar' => 6.00,
                'ingredients' => ['Beef chuck', 'Red wine', 'Mushrooms', 'Pearl onions', 'Carrots', 'Herbs'],
                'allergens' => ['Sulfites'],
                'is_dairy_free' => true,
                'prep_time_minutes' => 30,
                'cooking_time_minutes' => 120,
                'difficulty_level' => 4,
                'price' => 68.00,
                'weight_grams' => 480,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Lamb Tagine with Prunes',
                'slug' => 'lamb-tagine-prunes',
                'description' => 'Tender lamb slow-cooked with sweet prunes, honey and Moroccan spices',
                'short_description' => 'Moroccan lamb tagine',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 580,
                'protein' => 44.00,
                'carbohydrates' => 42.00,
                'fats' => 24.00,
                'fiber' => 6.00,
                'sodium' => 650.00,
                'sugar' => 18.00,
                'ingredients' => ['Lamb shoulder', 'Prunes', 'Honey', 'Almonds', 'Onions', 'Spices'],
                'allergens' => ['Tree nuts'],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 90,
                'difficulty_level' => 3,
                'price' => 72.00,
                'weight_grams' => 470,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Grilled Beef Steak with Potatoes',
                'slug' => 'grilled-beef-steak-potatoes',
                'description' => 'Premium beef steak grilled to perfection with roasted potatoes and green beans',
                'short_description' => 'Grilled beef steak',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 650,
                'protein' => 52.00,
                'carbohydrates' => 38.00,
                'fats' => 30.00,
                'fiber' => 5.00,
                'sodium' => 520.00,
                'sugar' => 3.00,
                'ingredients' => ['Beef steak', 'Potatoes', 'Green beans', 'Garlic', 'Herbs', 'Olive oil'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 25,
                'difficulty_level' => 2,
                'price' => 75.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Beef Meatballs in Tomato Sauce',
                'slug' => 'beef-meatballs-tomato-sauce',
                'description' => 'Homemade beef meatballs in rich tomato sauce served with pasta',
                'short_description' => 'Beef meatballs pasta',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 590,
                'protein' => 38.00,
                'carbohydrates' => 52.00,
                'fats' => 24.00,
                'fiber' => 5.00,
                'sodium' => 720.00,
                'sugar' => 8.00,
                'ingredients' => ['Ground beef', 'Tomatoes', 'Pasta', 'Onions', 'Garlic', 'Herbs', 'Breadcrumbs'],
                'allergens' => ['Gluten'],
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 35,
                'difficulty_level' => 2,
                'price' => 62.00,
                'weight_grams' => 500,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Lamb Chops with Mint Sauce',
                'slug' => 'lamb-chops-mint-sauce',
                'description' => 'Grilled lamb chops with fresh mint sauce and roasted vegetables',
                'short_description' => 'Grilled lamb chops',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 560,
                'protein' => 46.00,
                'carbohydrates' => 22.00,
                'fats' => 32.00,
                'fiber' => 4.00,
                'sodium' => 480.00,
                'sugar' => 5.00,
                'ingredients' => ['Lamb chops', 'Fresh mint', 'Yogurt', 'Zucchini', 'Bell peppers', 'Olive oil'],
                'allergens' => ['Dairy'],
                'is_gluten_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 20,
                'difficulty_level' => 3,
                'price' => 78.00,
                'weight_grams' => 420,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Fish Meals (Menu - Type 0) - 3 meals
            [
                'name' => 'Grilled Salmon with Lemon Butter',
                'slug' => 'grilled-salmon-lemon-butter',
                'description' => 'Fresh Atlantic salmon grilled with lemon butter sauce and asparagus',
                'short_description' => 'Grilled salmon fillet',
                'category_id' => $fishCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 480,
                'protein' => 42.00,
                'carbohydrates' => 18.00,
                'fats' => 26.00,
                'fiber' => 4.00,
                'sodium' => 420.00,
                'sugar' => 2.00,
                'ingredients' => ['Salmon fillet', 'Lemon', 'Butter', 'Asparagus', 'Dill', 'Olive oil'],
                'allergens' => ['Fish', 'Dairy'],
                'is_gluten_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 10,
                'cooking_time_minutes' => 15,
                'difficulty_level' => 2,
                'price' => 68.00,
                'weight_grams' => 380,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Mediterranean Sea Bass',
                'slug' => 'mediterranean-sea-bass',
                'description' => 'Baked sea bass with Mediterranean vegetables, olives and herbs',
                'short_description' => 'Mediterranean fish',
                'category_id' => $fishCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 420,
                'protein' => 38.00,
                'carbohydrates' => 24.00,
                'fats' => 18.00,
                'fiber' => 5.00,
                'sodium' => 520.00,
                'sugar' => 4.00,
                'ingredients' => ['Sea bass', 'Cherry tomatoes', 'Olives', 'Capers', 'Herbs', 'Olive oil'],
                'allergens' => ['Fish'],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 25,
                'difficulty_level' => 2,
                'price' => 72.00,
                'weight_grams' => 400,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Fish Tagine with Vegetables',
                'slug' => 'fish-tagine-vegetables',
                'description' => 'Traditional Moroccan fish tagine with seasonal vegetables and chermoula sauce',
                'short_description' => 'Moroccan fish tagine',
                'category_id' => $fishCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 390,
                'protein' => 36.00,
                'carbohydrates' => 28.00,
                'fats' => 14.00,
                'fiber' => 6.00,
                'sodium' => 580.00,
                'sugar' => 5.00,
                'ingredients' => ['White fish', 'Tomatoes', 'Bell peppers', 'Potatoes', 'Chermoula', 'Olives'],
                'allergens' => ['Fish'],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 3,
                'price' => 65.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Vegetarian Meals (Menu - Type 0) - 4 meals
            [
                'name' => 'Vegetable Buddha Bowl',
                'slug' => 'vegetable-buddha-bowl',
                'description' => 'Nutritious bowl with quinoa, roasted vegetables, chickpeas and tahini dressing',
                'short_description' => 'Healthy veggie bowl',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 450,
                'protein' => 18.00,
                'carbohydrates' => 62.00,
                'fats' => 16.00,
                'fiber' => 12.00,
                'sodium' => 420.00,
                'sugar' => 8.00,
                'ingredients' => ['Quinoa', 'Chickpeas', 'Sweet potato', 'Kale', 'Avocado', 'Tahini'],
                'allergens' => ['Sesame'],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 2,
                'price' => 42.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Vegetarian Moroccan Couscous',
                'slug' => 'vegetarian-moroccan-couscous',
                'description' => 'Traditional Moroccan couscous with seven vegetables and chickpeas',
                'short_description' => 'Vegetarian couscous',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 480,
                'protein' => 16.00,
                'carbohydrates' => 72.00,
                'fats' => 14.00,
                'fiber' => 10.00,
                'sodium' => 580.00,
                'sugar' => 12.00,
                'ingredients' => ['Couscous', 'Chickpeas', 'Zucchini', 'Carrots', 'Turnips', 'Raisins', 'Spices'],
                'allergens' => ['Gluten'],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 40,
                'difficulty_level' => 3,
                'price' => 38.00,
                'weight_grams' => 500,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Lentil Curry with Rice',
                'slug' => 'lentil-curry-rice',
                'description' => 'Hearty red lentil curry with aromatic spices and basmati rice',
                'short_description' => 'Spicy lentil curry',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 420,
                'protein' => 20.00,
                'carbohydrates' => 68.00,
                'fats' => 8.00,
                'fiber' => 14.00,
                'sodium' => 480.00,
                'sugar' => 6.00,
                'ingredients' => ['Red lentils', 'Coconut milk', 'Curry spices', 'Basmati rice', 'Tomatoes', 'Spinach'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_spicy' => true,
                'spice_level' => 2,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 2,
                'price' => 36.00,
                'weight_grams' => 480,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Stuffed Bell Peppers',
                'slug' => 'stuffed-bell-peppers',
                'description' => 'Colorful bell peppers stuffed with quinoa, vegetables and cheese',
                'short_description' => 'Veggie stuffed peppers',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 380,
                'protein' => 16.00,
                'carbohydrates' => 48.00,
                'fats' => 14.00,
                'fiber' => 8.00,
                'sodium' => 520.00,
                'sugar' => 10.00,
                'ingredients' => ['Bell peppers', 'Quinoa', 'Black beans', 'Corn', 'Cheese', 'Tomato sauce'],
                'allergens' => ['Dairy'],
                'is_vegetarian' => true,
                'is_gluten_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 35,
                'difficulty_level' => 2,
                'price' => 40.00,
                'weight_grams' => 420,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Breakfast Meals (Type 1) - 2 meals
            [
                'name' => 'Moroccan Msemen with Honey',
                'slug' => 'moroccan-msemen-honey',
                'description' => 'Traditional Moroccan pancakes served with honey and butter',
                'short_description' => 'Moroccan pancakes',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::BREAKFAST->value,
                'calories' => 380,
                'protein' => 8.00,
                'carbohydrates' => 58.00,
                'fats' => 14.00,
                'fiber' => 2.00,
                'sodium' => 280.00,
                'sugar' => 18.00,
                'ingredients' => ['Flour', 'Semolina', 'Butter', 'Honey', 'Salt', 'Yeast'],
                'allergens' => ['Gluten', 'Dairy'],
                'is_vegetarian' => true,
                'prep_time_minutes' => 30,
                'cooking_time_minutes' => 15,
                'difficulty_level' => 3,
                'price' => 22.00,
                'weight_grams' => 200,
                'serving_size' => '3 pieces',
                'is_active' => true,
            ],
            [
                'name' => 'Avocado Toast with Eggs',
                'slug' => 'avocado-toast-eggs',
                'description' => 'Whole grain toast topped with mashed avocado and poached eggs',
                'short_description' => 'Avocado & eggs toast',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::BREAKFAST->value,
                'calories' => 420,
                'protein' => 18.00,
                'carbohydrates' => 32.00,
                'fats' => 24.00,
                'fiber' => 8.00,
                'sodium' => 380.00,
                'sugar' => 3.00,
                'ingredients' => ['Whole grain bread', 'Avocado', 'Eggs', 'Cherry tomatoes', 'Olive oil'],
                'allergens' => ['Gluten', 'Eggs'],
                'is_vegetarian' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 10,
                'cooking_time_minutes' => 8,
                'difficulty_level' => 1,
                'price' => 28.00,
                'weight_grams' => 280,
                'serving_size' => '2 slices',
                'is_active' => true,
            ],

            // Drinks (Type 2) - 1 meal
            [
                'name' => 'Fresh Orange Juice',
                'slug' => 'fresh-orange-juice',
                'description' => 'Freshly squeezed orange juice, no added sugar',
                'short_description' => 'Fresh OJ',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 110,
                'protein' => 2.00,
                'carbohydrates' => 26.00,
                'fats' => 0.50,
                'fiber' => 0.50,
                'sodium' => 2.00,
                'sugar' => 21.00,
                'ingredients' => ['Fresh oranges'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 5,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 15.00,
                'weight_grams' => 250,
                'serving_size' => '250ml',
                'is_active' => true,
            ],
        ];

        foreach ($meals as $meal) {
            Meal::updateOrCreate(
                ['slug' => $meal['slug']],
                $meal
            );
        }

        $this->command->info('Meals seeded successfully: ' . count($meals) . ' meals created.');
    }
}
