<?php

namespace Database\Seeders;

use App\enum\MealCategory;
use App\Models\Category;
use App\Models\Meal;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MealsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category IDs
        $chickenCategory = Category::where('slug', 'chicken-meals')->first();
        $beefLambCategory = Category::where('slug', 'beef-lamb-meals')->first();
        $fishCategory = Category::where('slug', 'fish-meals')->first();
        $vegetarianCategory = Category::where('slug', 'vegetarian-meals')->first();

        if (!$chickenCategory || !$beefLambCategory || !$fishCategory || !$vegetarianCategory) {
            $this->command->error('Categories not found. Please run CategoriesSeeder first.');
            return;
        }

        $meals = [
            // Chicken Meals (Menu - Type 0) - 5 meals
            [
                'name' => 'Grilled Chicken Breast with Vegetables',
                'slug' => 'grilled-chicken-breast-vegetables',
                'description' => 'Tender grilled chicken breast served with seasonal roasted vegetables and herbs',
                'short_description' => 'Healthy grilled chicken with veggies',
                'category_id' => $chickenCategory->id,
                'calories' => 450,
                'protein' => 45.00,
                'carbohydrates' => 25.00,
                'fats' => 15.00,
                'fiber' => 6.00,
                'sodium' => 450.00,
                'sugar' => 4.00,
                'ingredients' => ['Chicken breast', 'Broccoli', 'Carrots', 'Olive oil', 'Herbs'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 25,
                'difficulty_level' => 2,
                'price' => 45.00,
                'weight_grams' => 400,
                'serving_size' => '1 portion',
                'is_active' => true,
                'is_membership' => true,
                'type_id' => MealCategory::MENU->value,

            ],
            [
                'name' => 'Chicken Tagine with Olives',
                'slug' => 'chicken-tagine-olives',
                'description' => 'Traditional Moroccan chicken tagine with olives, preserved lemons and aromatic spices',
                'short_description' => 'Moroccan chicken tagine',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 520,
                'protein' => 42.00,
                'carbohydrates' => 35.00,
                'fats' => 22.00,
                'fiber' => 5.00,
                'sodium' => 680.00,
                'sugar' => 6.00,
                'ingredients' => ['Chicken thighs', 'Green olives', 'Preserved lemons', 'Onions', 'Spices'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 45,
                'difficulty_level' => 3,
                'price' => 52.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
                'is_membership' => true,

            ],
            [
                'name' => 'Chicken Curry with Rice',
                'slug' => 'chicken-curry-rice',
                'description' => 'Creamy chicken curry with aromatic spices served with basmati rice',
                'short_description' => 'Spicy chicken curry',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 580,
                'protein' => 38.00,
                'carbohydrates' => 62.00,
                'fats' => 18.00,
                'fiber' => 4.00,
                'sodium' => 720.00,
                'sugar' => 5.00,
                'ingredients' => ['Chicken', 'Coconut milk', 'Curry spices', 'Basmati rice', 'Onions', 'Tomatoes'],
                'allergens' => [],
                'is_spicy' => true,
                'spice_level' => 3,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 2,
                'price' => 48.00,
                'weight_grams' => 500,
                'serving_size' => '1 portion',
                'is_active' => true,
                'is_membership' => true,

            ],
            [
                'name' => 'Lemon Herb Chicken Skewers',
                'slug' => 'lemon-herb-chicken-skewers',
                'description' => 'Marinated chicken skewers with lemon and fresh herbs, served with quinoa',
                'short_description' => 'Grilled chicken skewers',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 420,
                'protein' => 40.00,
                'carbohydrates' => 28.00,
                'fats' => 14.00,
                'fiber' => 5.00,
                'sodium' => 380.00,
                'sugar' => 2.00,
                'ingredients' => ['Chicken breast', 'Lemon', 'Herbs', 'Quinoa', 'Bell peppers'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 15,
                'difficulty_level' => 2,
                'price' => 46.00,
                'weight_grams' => 380,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Chicken Pasta Alfredo',
                'slug' => 'chicken-pasta-alfredo',
                'description' => 'Creamy Alfredo pasta with grilled chicken and parmesan cheese',
                'short_description' => 'Creamy chicken pasta',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 680,
                'protein' => 42.00,
                'carbohydrates' => 58.00,
                'fats' => 32.00,
                'fiber' => 3.00,
                'sodium' => 820.00,
                'sugar' => 4.00,
                'ingredients' => ['Chicken breast', 'Pasta', 'Heavy cream', 'Parmesan', 'Garlic', 'Butter'],
                'allergens' => ['Gluten', 'Dairy'],
                'prep_time_minutes' => 10,
                'cooking_time_minutes' => 20,
                'difficulty_level' => 2,
                'price' => 50.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Beef/Lamb Meals (Menu - Type 0) - 5 meals
            [
                'name' => 'Beef Bourguignon',
                'slug' => 'beef-bourguignon',
                'description' => 'Classic French beef stew braised in red wine with mushrooms and pearl onions',
                'short_description' => 'French beef stew',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 620,
                'protein' => 48.00,
                'carbohydrates' => 32.00,
                'fats' => 28.00,
                'fiber' => 4.00,
                'sodium' => 780.00,
                'sugar' => 6.00,
                'ingredients' => ['Beef chuck', 'Red wine', 'Mushrooms', 'Pearl onions', 'Carrots', 'Herbs'],
                'allergens' => ['Sulfites'],
                'is_dairy_free' => true,
                'prep_time_minutes' => 30,
                'cooking_time_minutes' => 120,
                'difficulty_level' => 4,
                'price' => 68.00,
                'weight_grams' => 480,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Lamb Tagine with Prunes',
                'slug' => 'lamb-tagine-prunes',
                'description' => 'Tender lamb slow-cooked with sweet prunes, honey and Moroccan spices',
                'short_description' => 'Moroccan lamb tagine',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 580,
                'protein' => 44.00,
                'carbohydrates' => 42.00,
                'fats' => 24.00,
                'fiber' => 6.00,
                'sodium' => 650.00,
                'sugar' => 18.00,
                'ingredients' => ['Lamb shoulder', 'Prunes', 'Honey', 'Almonds', 'Onions', 'Spices'],
                'allergens' => ['Tree nuts'],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 90,
                'difficulty_level' => 3,
                'price' => 72.00,
                'weight_grams' => 470,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Grilled Beef Steak with Potatoes',
                'slug' => 'grilled-beef-steak-potatoes',
                'description' => 'Premium beef steak grilled to perfection with roasted potatoes and green beans',
                'short_description' => 'Grilled beef steak',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 650,
                'protein' => 52.00,
                'carbohydrates' => 38.00,
                'fats' => 30.00,
                'fiber' => 5.00,
                'sodium' => 520.00,
                'sugar' => 3.00,
                'ingredients' => ['Beef steak', 'Potatoes', 'Green beans', 'Garlic', 'Herbs', 'Olive oil'],
                'allergens' => [],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 25,
                'difficulty_level' => 2,
                'price' => 75.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Beef Meatballs in Tomato Sauce',
                'slug' => 'beef-meatballs-tomato-sauce',
                'description' => 'Homemade beef meatballs in rich tomato sauce served with pasta',
                'short_description' => 'Beef meatballs pasta',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 590,
                'protein' => 38.00,
                'carbohydrates' => 52.00,
                'fats' => 24.00,
                'fiber' => 5.00,
                'sodium' => 720.00,
                'sugar' => 8.00,
                'ingredients' => ['Ground beef', 'Tomatoes', 'Pasta', 'Onions', 'Garlic', 'Herbs', 'Breadcrumbs'],
                'allergens' => ['Gluten'],
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 35,
                'difficulty_level' => 2,
                'price' => 62.00,
                'weight_grams' => 500,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Lamb Chops with Mint Sauce',
                'slug' => 'lamb-chops-mint-sauce',
                'description' => 'Grilled lamb chops with fresh mint sauce and roasted vegetables',
                'short_description' => 'Grilled lamb chops',
                'category_id' => $beefLambCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 560,
                'protein' => 46.00,
                'carbohydrates' => 22.00,
                'fats' => 32.00,
                'fiber' => 4.00,
                'sodium' => 480.00,
                'sugar' => 5.00,
                'ingredients' => ['Lamb chops', 'Fresh mint', 'Yogurt', 'Zucchini', 'Bell peppers', 'Olive oil'],
                'allergens' => ['Dairy'],
                'is_gluten_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 20,
                'difficulty_level' => 3,
                'price' => 78.00,
                'weight_grams' => 420,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Fish Meals (Menu - Type 0) - 3 meals
            [
                'name' => 'Grilled Salmon with Lemon Butter',
                'slug' => 'grilled-salmon-lemon-butter',
                'description' => 'Fresh Atlantic salmon grilled with lemon butter sauce and asparagus',
                'short_description' => 'Grilled salmon fillet',
                'category_id' => $fishCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 480,
                'protein' => 42.00,
                'carbohydrates' => 18.00,
                'fats' => 26.00,
                'fiber' => 4.00,
                'sodium' => 420.00,
                'sugar' => 2.00,
                'ingredients' => ['Salmon fillet', 'Lemon', 'Butter', 'Asparagus', 'Dill', 'Olive oil'],
                'allergens' => ['Fish', 'Dairy'],
                'is_gluten_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 10,
                'cooking_time_minutes' => 15,
                'difficulty_level' => 2,
                'price' => 68.00,
                'weight_grams' => 380,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Mediterranean Sea Bass',
                'slug' => 'mediterranean-sea-bass',
                'description' => 'Baked sea bass with Mediterranean vegetables, olives and herbs',
                'short_description' => 'Mediterranean fish',
                'category_id' => $fishCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 420,
                'protein' => 38.00,
                'carbohydrates' => 24.00,
                'fats' => 18.00,
                'fiber' => 5.00,
                'sodium' => 520.00,
                'sugar' => 4.00,
                'ingredients' => ['Sea bass', 'Cherry tomatoes', 'Olives', 'Capers', 'Herbs', 'Olive oil'],
                'allergens' => ['Fish'],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 25,
                'difficulty_level' => 2,
                'price' => 72.00,
                'weight_grams' => 400,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Fish Tagine with Vegetables',
                'slug' => 'fish-tagine-vegetables',
                'description' => 'Traditional Moroccan fish tagine with seasonal vegetables and chermoula sauce',
                'short_description' => 'Moroccan fish tagine',
                'category_id' => $fishCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 390,
                'protein' => 36.00,
                'carbohydrates' => 28.00,
                'fats' => 14.00,
                'fiber' => 6.00,
                'sodium' => 580.00,
                'sugar' => 5.00,
                'ingredients' => ['White fish', 'Tomatoes', 'Bell peppers', 'Potatoes', 'Chermoula', 'Olives'],
                'allergens' => ['Fish'],
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 3,
                'price' => 65.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Vegetarian Meals (Menu - Type 0) - 4 meals
            [
                'name' => 'Vegetable Buddha Bowl',
                'slug' => 'vegetable-buddha-bowl',
                'description' => 'Nutritious bowl with quinoa, roasted vegetables, chickpeas and tahini dressing',
                'short_description' => 'Healthy veggie bowl',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 450,
                'protein' => 18.00,
                'carbohydrates' => 62.00,
                'fats' => 16.00,
                'fiber' => 12.00,
                'sodium' => 420.00,
                'sugar' => 8.00,
                'ingredients' => ['Quinoa', 'Chickpeas', 'Sweet potato', 'Kale', 'Avocado', 'Tahini'],
                'allergens' => ['Sesame'],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 2,
                'price' => 42.00,
                'weight_grams' => 450,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Vegetarian Moroccan Couscous',
                'slug' => 'vegetarian-moroccan-couscous',
                'description' => 'Traditional Moroccan couscous with seven vegetables and chickpeas',
                'short_description' => 'Vegetarian couscous',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 480,
                'protein' => 16.00,
                'carbohydrates' => 72.00,
                'fats' => 14.00,
                'fiber' => 10.00,
                'sodium' => 580.00,
                'sugar' => 12.00,
                'ingredients' => ['Couscous', 'Chickpeas', 'Zucchini', 'Carrots', 'Turnips', 'Raisins', 'Spices'],
                'allergens' => ['Gluten'],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 40,
                'difficulty_level' => 3,
                'price' => 38.00,
                'weight_grams' => 500,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Lentil Curry with Rice',
                'slug' => 'lentil-curry-rice',
                'description' => 'Hearty red lentil curry with aromatic spices and basmati rice',
                'short_description' => 'Spicy lentil curry',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 420,
                'protein' => 20.00,
                'carbohydrates' => 68.00,
                'fats' => 8.00,
                'fiber' => 14.00,
                'sodium' => 480.00,
                'sugar' => 6.00,
                'ingredients' => ['Red lentils', 'Coconut milk', 'Curry spices', 'Basmati rice', 'Tomatoes', 'Spinach'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_spicy' => true,
                'spice_level' => 2,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 30,
                'difficulty_level' => 2,
                'price' => 36.00,
                'weight_grams' => 480,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Stuffed Bell Peppers',
                'slug' => 'stuffed-bell-peppers',
                'description' => 'Colorful bell peppers stuffed with quinoa, vegetables and cheese',
                'short_description' => 'Veggie stuffed peppers',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::MENU->value,
                'calories' => 380,
                'protein' => 16.00,
                'carbohydrates' => 48.00,
                'fats' => 14.00,
                'fiber' => 8.00,
                'sodium' => 520.00,
                'sugar' => 10.00,
                'ingredients' => ['Bell peppers', 'Quinoa', 'Black beans', 'Corn', 'Cheese', 'Tomato sauce'],
                'allergens' => ['Dairy'],
                'is_vegetarian' => true,
                'is_gluten_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 35,
                'difficulty_level' => 2,
                'price' => 40.00,
                'weight_grams' => 420,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],

            // Breakfast Meals (Type 1) - 2 meals
            [
                'name' => 'Moroccan Msemen with Honey',
                'slug' => 'moroccan-msemen-honey',
                'description' => 'Traditional Moroccan pancakes served with honey and butter',
                'short_description' => 'Moroccan pancakes',
                'category_id' => $chickenCategory->id,
                'type_id' => MealCategory::BREAKFAST->value,
                'calories' => 380,
                'protein' => 8.00,
                'carbohydrates' => 58.00,
                'fats' => 14.00,
                'fiber' => 2.00,
                'sodium' => 280.00,
                'sugar' => 18.00,
                'ingredients' => ['Flour', 'Semolina', 'Butter', 'Honey', 'Salt', 'Yeast'],
                'allergens' => ['Gluten', 'Dairy'],
                'is_vegetarian' => true,
                'prep_time_minutes' => 30,
                'cooking_time_minutes' => 15,
                'difficulty_level' => 3,
                'price' => 22.00,
                'weight_grams' => 200,
                'serving_size' => '3 pieces',
                'is_active' => true,
            ],
            [
                'name' => 'Avocado Toast with Eggs',
                'slug' => 'avocado-toast-eggs',
                'description' => 'Whole grain toast topped with mashed avocado and poached eggs',
                'short_description' => 'Avocado & eggs toast',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::BREAKFAST->value,
                'calories' => 420,
                'protein' => 18.00,
                'carbohydrates' => 32.00,
                'fats' => 24.00,
                'fiber' => 8.00,
                'sodium' => 380.00,
                'sugar' => 3.00,
                'ingredients' => ['Whole grain bread', 'Avocado', 'Eggs', 'Cherry tomatoes', 'Olive oil'],
                'allergens' => ['Gluten', 'Eggs'],
                'is_vegetarian' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 10,
                'cooking_time_minutes' => 8,
                'difficulty_level' => 1,
                'price' => 28.00,
                'weight_grams' => 280,
                'serving_size' => '2 slices',
                'is_active' => true,
            ],

            // Drinks (Type 2) - 8 drinks
            [
                'name' => 'Fresh Orange Juice',
                'slug' => 'fresh-orange-juice',
                'description' => 'Freshly squeezed orange juice, no added sugar',
                'short_description' => 'Fresh OJ',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 110,
                'protein' => 2.00,
                'carbohydrates' => 26.00,
                'fats' => 0.50,
                'fiber' => 0.50,
                'sodium' => 2.00,
                'sugar' => 21.00,
                'ingredients' => ['Fresh oranges'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 5,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 15.00,
                'weight_grams' => 250,
                'serving_size' => '250ml',
                'is_active' => true,
            ],
            [
                'name' => 'Moroccan Mint Tea',
                'slug' => 'moroccan-mint-tea',
                'description' => 'Traditional Moroccan green tea with fresh mint leaves',
                'short_description' => 'Mint tea',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 40,
                'protein' => 0.00,
                'carbohydrates' => 10.00,
                'fats' => 0.00,
                'fiber' => 0.00,
                'sodium' => 5.00,
                'sugar' => 9.00,
                'ingredients' => ['Green tea', 'Fresh mint', 'Sugar'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 3,
                'cooking_time_minutes' => 5,
                'difficulty_level' => 1,
                'price' => 12.00,
                'weight_grams' => 200,
                'serving_size' => '200ml',
                'is_active' => true,
            ],
            [
                'name' => 'Green Smoothie',
                'slug' => 'green-smoothie',
                'description' => 'Healthy blend of spinach, banana, mango and coconut water',
                'short_description' => 'Green power smoothie',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 180,
                'protein' => 3.00,
                'carbohydrates' => 42.00,
                'fats' => 1.00,
                'fiber' => 5.00,
                'sodium' => 35.00,
                'sugar' => 28.00,
                'ingredients' => ['Spinach', 'Banana', 'Mango', 'Coconut water', 'Chia seeds'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 5,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 22.00,
                'weight_grams' => 350,
                'serving_size' => '350ml',
                'is_active' => true,
            ],
            [
                'name' => 'Berry Protein Smoothie',
                'slug' => 'berry-protein-smoothie',
                'description' => 'Mixed berries blended with protein powder and almond milk',
                'short_description' => 'Protein berry smoothie',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 220,
                'protein' => 18.00,
                'carbohydrates' => 32.00,
                'fats' => 4.00,
                'fiber' => 6.00,
                'sodium' => 120.00,
                'sugar' => 20.00,
                'ingredients' => ['Mixed berries', 'Protein powder', 'Almond milk', 'Banana', 'Honey'],
                'allergens' => ['Tree nuts'],
                'is_vegetarian' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'is_high_protein' => true,
                'prep_time_minutes' => 5,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 28.00,
                'weight_grams' => 400,
                'serving_size' => '400ml',
                'is_active' => true,
            ],
            [
                'name' => 'Fresh Lemonade',
                'slug' => 'fresh-lemonade',
                'description' => 'Homemade lemonade with fresh lemons and mint',
                'short_description' => 'Fresh lemonade',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 90,
                'protein' => 0.50,
                'carbohydrates' => 24.00,
                'fats' => 0.00,
                'fiber' => 0.50,
                'sodium' => 8.00,
                'sugar' => 20.00,
                'ingredients' => ['Fresh lemons', 'Water', 'Sugar', 'Mint'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 5,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 14.00,
                'weight_grams' => 300,
                'serving_size' => '300ml',
                'is_active' => true,
            ],
            [
                'name' => 'Cold Brew Coffee',
                'slug' => 'cold-brew-coffee',
                'description' => 'Smooth cold brew coffee, served with ice',
                'short_description' => 'Cold brew',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 5,
                'protein' => 0.00,
                'carbohydrates' => 0.00,
                'fats' => 0.00,
                'fiber' => 0.00,
                'sodium' => 10.00,
                'sugar' => 0.00,
                'ingredients' => ['Coffee beans', 'Water', 'Ice'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 2,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 18.00,
                'weight_grams' => 250,
                'serving_size' => '250ml',
                'is_active' => true,
            ],
            [
                'name' => 'Mango Lassi',
                'slug' => 'mango-lassi',
                'description' => 'Traditional Indian yogurt drink with fresh mango',
                'short_description' => 'Mango lassi',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 160,
                'protein' => 6.00,
                'carbohydrates' => 32.00,
                'fats' => 2.50,
                'fiber' => 1.00,
                'sodium' => 80.00,
                'sugar' => 28.00,
                'ingredients' => ['Fresh mango', 'Yogurt', 'Milk', 'Cardamom', 'Honey'],
                'allergens' => ['Dairy'],
                'is_vegetarian' => true,
                'is_gluten_free' => true,
                'prep_time_minutes' => 5,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 20.00,
                'weight_grams' => 300,
                'serving_size' => '300ml',
                'is_active' => true,
            ],
            [
                'name' => 'Detox Water',
                'slug' => 'detox-water',
                'description' => 'Infused water with cucumber, lemon, and fresh herbs',
                'short_description' => 'Detox infused water',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DRINKS->value,
                'calories' => 10,
                'protein' => 0.00,
                'carbohydrates' => 2.50,
                'fats' => 0.00,
                'fiber' => 0.50,
                'sodium' => 5.00,
                'sugar' => 1.50,
                'ingredients' => ['Water', 'Cucumber', 'Lemon', 'Mint', 'Ginger'],
                'allergens' => [],
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_dairy_free' => true,
                'prep_time_minutes' => 3,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 1,
                'price' => 10.00,
                'weight_grams' => 350,
                'serving_size' => '350ml',
                'is_active' => true,
            ],

            // Desserts (Menu category but can be identified by name/tags) - 6 desserts
            [
                'name' => 'Tiramisu',
                'slug' => 'tiramisu',
                'description' => 'Classic Italian dessert with coffee-soaked ladyfingers and mascarpone cream',
                'short_description' => 'Italian tiramisu',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DESSERTS->value,
                'calories' => 320,
                'protein' => 6.00,
                'carbohydrates' => 38.00,
                'fats' => 16.00,
                'fiber' => 1.00,
                'sodium' => 120.00,
                'sugar' => 24.00,
                'ingredients' => ['Ladyfingers', 'Mascarpone', 'Eggs', 'Coffee', 'Cocoa powder', 'Sugar'],
                'allergens' => ['Gluten', 'Dairy', 'Eggs'],
                'is_vegetarian' => true,
                'prep_time_minutes' => 30,
                'cooking_time_minutes' => 0,
                'difficulty_level' => 3,
                'price' => 32.00,
                'weight_grams' => 180,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
            [
                'name' => 'Chocolate Lava Cake',
                'slug' => 'chocolate-lava-cake',
                'description' => 'Decadent chocolate cake with molten chocolate center',
                'short_description' => 'Molten chocolate cake',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DESSERTS->value,
                'calories' => 380,
                'protein' => 7.00,
                'carbohydrates' => 42.00,
                'fats' => 22.00,
                'fiber' => 3.00,
                'sodium' => 180.00,
                'sugar' => 32.00,
                'ingredients' => ['Dark chocolate', 'Butter', 'Eggs', 'Flour', 'Sugar', 'Vanilla'],
                'allergens' => ['Gluten', 'Dairy', 'Eggs'],
                'is_vegetarian' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 12,
                'difficulty_level' => 3,
                'price' => 35.00,
                'weight_grams' => 150,
                'serving_size' => '1 cake',
                'is_active' => true,
            ],
            [
                'name' => 'Moroccan Baklava',
                'slug' => 'moroccan-baklava',
                'description' => 'Sweet pastry with layers of phyllo, honey, and mixed nuts',
                'short_description' => 'Honey nut baklava',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DESSERTS->value,
                'calories' => 280,
                'protein' => 5.00,
                'carbohydrates' => 36.00,
                'fats' => 14.00,
                'fiber' => 2.00,
                'sodium' => 95.00,
                'sugar' => 22.00,
                'ingredients' => ['Phyllo dough', 'Almonds', 'Pistachios', 'Honey', 'Butter', 'Cinnamon'],
                'allergens' => ['Gluten', 'Dairy', 'Tree nuts'],
                'is_vegetarian' => true,
                'prep_time_minutes' => 40,
                'cooking_time_minutes' => 35,
                'difficulty_level' => 4,
                'price' => 28.00,
                'weight_grams' => 120,
                'serving_size' => '3 pieces',
                'is_active' => true,
            ],
            [
                'name' => 'Crème Brûlée',
                'slug' => 'creme-brulee',
                'description' => 'Classic French custard with caramelized sugar topping',
                'short_description' => 'French custard',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DESSERTS->value,
                'calories' => 290,
                'protein' => 5.00,
                'carbohydrates' => 28.00,
                'fats' => 18.00,
                'fiber' => 0.00,
                'sodium' => 85.00,
                'sugar' => 24.00,
                'ingredients' => ['Heavy cream', 'Egg yolks', 'Sugar', 'Vanilla bean'],
                'allergens' => ['Dairy', 'Eggs'],
                'is_vegetarian' => true,
                'is_gluten_free' => true,
                'prep_time_minutes' => 20,
                'cooking_time_minutes' => 45,
                'difficulty_level' => 3,
                'price' => 30.00,
                'weight_grams' => 140,
                'serving_size' => '1 ramekin',
                'is_active' => true,
            ],
            [
                'name' => 'Cheesecake Slice',
                'slug' => 'cheesecake-slice',
                'description' => 'Creamy New York style cheesecake with berry compote',
                'short_description' => 'Classic cheesecake',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DESSERTS->value,
                'calories' => 340,
                'protein' => 8.00,
                'carbohydrates' => 34.00,
                'fats' => 20.00,
                'fiber' => 1.00,
                'sodium' => 260.00,
                'sugar' => 26.00,
                'ingredients' => ['Cream cheese', 'Graham crackers', 'Butter', 'Eggs', 'Sugar', 'Mixed berries'],
                'allergens' => ['Gluten', 'Dairy', 'Eggs'],
                'is_vegetarian' => true,
                'prep_time_minutes' => 25,
                'cooking_time_minutes' => 60,
                'difficulty_level' => 3,
                'price' => 34.00,
                'weight_grams' => 160,
                'serving_size' => '1 slice',
                'is_active' => true,
            ],
            [
                'name' => 'Panna Cotta',
                'slug' => 'panna-cotta',
                'description' => 'Silky Italian cream dessert with vanilla and fresh berries',
                'short_description' => 'Italian cream dessert',
                'category_id' => $vegetarianCategory->id,
                'type_id' => MealCategory::DESSERTS->value,
                'calories' => 260,
                'protein' => 4.00,
                'carbohydrates' => 24.00,
                'fats' => 16.00,
                'fiber' => 1.00,
                'sodium' => 65.00,
                'sugar' => 20.00,
                'ingredients' => ['Heavy cream', 'Milk', 'Sugar', 'Vanilla', 'Gelatin', 'Fresh berries'],
                'allergens' => ['Dairy'],
                'is_vegetarian' => true,
                'is_gluten_free' => true,
                'prep_time_minutes' => 15,
                'cooking_time_minutes' => 5,
                'difficulty_level' => 2,
                'price' => 26.00,
                'weight_grams' => 150,
                'serving_size' => '1 portion',
                'is_active' => true,
            ],
        ];

        foreach ($meals as $meal) {
            Meal::create($meal);
        }

        $this->command->info('Meals seeded successfully: ' . count($meals) . ' meals created.');
    }
}
